model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"

[projects."/Users/demfabris/Documents/Development/Clairvo/backend"]
trust_level = "trusted"

[projects."/Users/demfabris/Documents/Development/Clairvo/frontend"]
trust_level = "trusted"

[projects."/Users/demfabris"]
trust_level = "trusted"

[features]
unified_exec = true
shell_snapshot = true
steer = true

